#!/bin/bash
# This is a terrible, brittle way to extract data from an HTML page, but hey,
# it works and was quick to write.  When it breaks and annoys me too much, I'll
# do it properly with a real HTML parser.
#
set -e -o pipefail

url='http://www2.seattle.gov/fire/realtime911/getRecsForDatePub.asp?action=Today&incDate=&rad1=des'

# Header row
paste -s <<.
timestamp
incident_number
level
units
location
incident_type
.

# Active incidents
curl -fsS "$url" \
    | grep -E 'td[^>]+\bactive\b' \
    | perl -nE '/>(.+)<\/td>\s*$/ and say $1' \
    | perl -nE 'chomp; push @lines, $_; say(join "\t", @lines), @lines = () if $. % 6 == 0 or eof;'
