#!/bin/bash
set -e -o pipefail

recs fromcsv -d $'\t' --header data/active-incidents.tsv \
    | recs decollate -d split,units,' ',unit \
    | recs collate -k unit \
    | recs join --right unit apparatus <(recs fromcsv --header data/apparatus-locations.csv) \
    | recs grep -v '{{station}}' \
    | recs eval '{{apparatus}}'
